"""empty message

Revision ID: 13709c859721
Revises: 
Create Date: 2025-05-25 23:05:12.257149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13709c859721'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description_new', sa.Text(), nullable=True),
    sa.Column('img', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description_teacher', sa.Text(), nullable=True),
    sa.Column('img', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher')
    op.drop_table('news')
    # ### end Alembic commands ###
